#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from os import listdir
import re
import sys
from argparse import ArgumentParser
import random
import subprocess
from math import sqrt
import pymol

import __main__
__main__.pymol_argv = [ 'pymol', '-qc'] # Quiet and no GUI

import time, os

pymol.finish_launching()
pymol.cmd.load("mod08.pdb")
pymol.cmd.load("mod10.pdb")
pymol.cmd.run ("fitting.py")
pymol.fitting("mod08", "c. a" , "mod10", "c. a")
#pymol.cmd.quit()
